List<String> allSkills = [
  "3D Animator",
  "3D Modeler",
  "Accountant",
  "Actor",
  "AdTech Developer",
  "AdTech Specialist",
  "AI Engineer",
  "AI Ethics Specialist",
  "AI Researcher",
  "Air Traffic Controller",
  "Android Developer",
  "Animator",
  "Anthropologist",
  "Architect",
  "Art Director",
  "Astronomer",
  "Audio Engineer",
  "Augmented Reality Developer",
  "Automotive Engineer",
  "Backend Architect",
  "Backend Developer",
  "Baker",
  "Barista",
  "Bartender",
  "Big Data Engineer",
  "Bioinformatics Specialist",
  "Biomedical Engineer",
  "Blockchain Developer",
  "Blacksmith",
  "Bus Driver",
  "C# Developer",
  "C++ Developer",
  "Carpenter",
  "Cartoonist",
  "Caterer",
  "CEO",
  "Charity Worker",
  "Chef",
  "Chemical Engineer",
  "Chief Information Officer (CIO)",
  "Chief Technology Officer (CTO)",
  "Chiropractor",
  "Cloud Engineer",
  "Cloud Security Engineer",
  "Cloud Solutions Architect",
  "CMS Developer",
  "Comedian",
  "Computer Vision Engineer",
  "Construction Manager",
  "Content Writer",
  "Copywriter",
  "CRM Developer",
  "Cyber Forensics Analyst",
  "Cybersecurity Analyst",
  "Data Analyst",
  "Data Engineer",
  "Data Governance Specialist",
  "Data Scientist",
  "Database Administrator",
  "Deep Learning Engineer",
  "Delivery Driver",
  "Dentist",
  "DevOps Engineer",
  "DevSecOps Engineer",
  "Digital Marketing Specialist",
  "Digital Product Manager",
  "Digital Transformation Consultant",
  "DJ",
  "Doctor",
  "Django Developer",
  "E-learning Developer",
  "Economist",
  "Edge Computing Engineer",
  "Editor",
  "Electrician",
  "Electrical Engineer",
  "Embedded Systems Engineer",
  "Email Marketing Specialist",
  "e-Learning Developer",
  "Environmental Engineer",
  "Environmental Scientist",
  "ERP Consultant",
  "Ethical AI Researcher",
  "Ethical Hacker",
  "Ethical Hacking Instructor",
  "Event Planner",
  "Fashion Designer",
  "Farmer",
  "Filmmaker",
  "FinTech Developer",
  "Firefighter",
  "Firmware Developer",
  "Florist",
  "Flight Attendant",
  "Flutter Developer",
  "Frontend Architect",
  "Frontend Developer",
  "Full Stack Developer",
  "Fundraiser",
  "Futurist",
  "Game Designer",
  "Game Developer",
  "Gardener",
  "Geotechnical Engineer",
  "GIS Developer",
  "Glass Installer",
  "Go Developer",
  "Government Official",
  "Graphic Designer",
  "Hardware Engineer",
  "Hardware Technician",
  "HealthTech Developer",
  "Help Desk Technician",
  "Historian",
  "Home Inspector",
  "Hotel Manager",
  "HR Manager",
  "HVAC Technician",
  "Industrial Designer",
  "Information Security Analyst",
  "Influencer Marketing Manager",
  "Infrastructure Engineer",
  "Insurance Agent",
  "Interior Designer",
  "Interpreter",
  "Investment Banker",
  "IoT Developer",
  "iOS Developer",
  "IT Auditor",
  "IT Business Analyst",
  "IT Compliance Specialist",
  "IT Consultant",
  "IT Governance Analyst",
  "IT Project Manager",
  "IT Procurement Specialist",
  "IT Risk Analyst",
  "IT Sales Engineer",
  "IT Security Specialist",
  "IT Support Specialist",
  "IT Trainer",
  "Jewelry Designer",
  "Journalist",
  "Judge",
  "Kotlin Developer",
  "Land Surveyor",
  "Landscaper",
  "Laravel Developer",
  "Lawyer",
  "Learning Management System (LMS) Developer",
  "Legal Consultant",
  "Librarian",
  "Locksmith",
  "Logistics Coordinator",
  "Machine Learning Engineer",
  "Magento Developer",
  "Maintenance Technician",
  "Makeup Artist",
  "Manicurist",
  "Manufacturing Engineer",
  "Marine Biologist",
  "Marketing Manager",
  "Mason",
  "Mathematician",
  "Mechanical Engineer",
  "MedTech Engineer",
  "Meteorologist",
  "Military Officer",
  "Mining Engineer",
  "Mobile App Developer",
  "Motion Graphics Designer",
  "Museum Curator",
  "Musician",
  "Network Administrator",
  "Networking Engineer",
  "NGO Coordinator",
  "NLP Engineer",
  "NoSQL Developer",
  "Nurse",
  "Nutritionist",
  "Occupational Therapist",
  "Oil and Gas Engineer",
  "Optometrist",
  "Painter",
  "Paramedic",
  "Penetration Tester",
  "Personal Trainer",
  "Pharmacist",
  "Photographer",
  "PHP Developer",
  "Physicist",
  "Pilot",
  "Plumber",
  "Poet",
  "Political Analyst",
  "Post-Production Specialist",
  "Product Designer",
  "Professor",
  "Property Manager",
  "Psychologist",
  "Public Relations Specialist",
  "Python Developer",
  "Quantum Computing Researcher",
  "React Developer",
  "React Native Developer",
  "Real Estate Agent",
  "Recruiter",
  "Renewable Energy Engineer",
  "Roofer",
  "RPA Developer",
  "Ruby on Rails Developer",
  "Rust Developer",
  "SAP Consultant",
  "Scrum Master",
  "Search Engine Optimization (SEO) Specialist",
  "Security Guard",
  "Security Software Developer",
  "SEO Specialist",
  "Shopify Developer",
  "Singer",
  "Smart Contract Developer",
  "Smart Home Engineer",
  "Social Media Manager",
  "Software Developer",
  "Software Engineer",
  "Solar Panel Technician",
  "Sound Engineer",
  "Space Scientist",
  "Statistician",
  "Streaming Engineer",
  "Structural Engineer",
  "Supply Chain Manager",
  "Surgeon",
  "Swift Developer",
  "Tailor",
  "Taxi Driver",
  "Teacher",
  "Technical Recruiter",
  "Technical Writer",
  "Telecommunication Engineer",
  "Textile Designer",
  "Tour Guide",
  "Traffic Controller",
  "Translator",
  "Truck Driver",
  "TypeScript Developer",
  "UI Designer",
  "UI Motion Designer",
  "UI/UX Designer",
  "Urban Planner",
  "User Experience (UX) Designer",
  "UX Designer",
  "Veterinarian",
  "Video Editor",
  "Videographer",
  "Virtual Assistant Developer",
  "Virtual Reality Developer",
  "Vue.js Developer",
  "Waiter",
  "Warehouse Manager",
  "Web Developer",
  "Wedding Planner",
  "Welder",
  "WordPress Developer",
  "Writer",
  "Yoga Instructor",
  "Zoologist"
];
Map<String, List<String>> relatedSkills = {
  "Flutter Developer": [
    "Mobile App Developer",
    "React Native Developer",
    "Android Developer",
    "iOS Developer"
  ],
  "Mobile App Developer": [
    "Flutter Developer",
    "Android Developer",
    "Java Developer",
    "Kotlin Developer",
    "iOS Developer",
    "React Native Developer"
  ],
  "Android Developer": [
    "Software Developer",
    "Mobile App Developer",
    "Flutter Developer",
    "Java Developer",
    "Kotlin Developer"
  ],
  "iOS Developer": [
    "Mobile App Developer",
    "Swift Developer",
    "Objective-C Developer"
  ],
  "React Native Developer": [
    "Mobile App Developer",
    "Flutter Developer",
    "JavaScript Developer"
  ],
  "Web Developer": [
    "Software Developer",
     "Software Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Full-Stack Developer",
    "JavaScript Developer"
  ],
  "Frontend Developer": [
    "Software Developer",
    "Web Developer",
    "UI/UX Designer",
    "JavaScript Developer",
    "React Developer"
  ],
  "Backend Developer": [
    "Software Developer",
    "Web Developer",
    "Full-Stack Developer",
    "Database Administrator",
    "API Developer"
  ],
  "Full-Stack Developer": [
    "Web Developer",
    "Frontend Developer",
    "Backend Developer",
    "Software Engineer"
  ],
  "Java Developer": [
    "Backend Developer",
    "Android Developer",
    "Software Engineer"
  ],
  "Software Engineer": [
    "Full-Stack Developer",
    "Java Developer",
    "C++ Developer",
    "Python Developer"
  ],
  "Python Developer": [
    "Data Scientist",
    "Machine Learning Engineer",
    "Backend Developer",
    "Django"
  ],
  "Machine Learning Engineer": [
    "Data Scientist",
    "AI Engineer",
    "Python Developer"
  ],
  "Data Scientist": [
    "Machine Learning Engineer",
    "Big Data Engineer",
    "Python Developer"
  ],
  "Cybersecurity Analyst": [
    "Penetration Tester",
    "Ethical Hacker",
    "IT Security Specialist"
  ],
  "Penetration Tester": [
    "Ethical Hacker",
    "Cybersecurity Analyst",
    "Security Researcher"
  ],
  "Ethical Hacker": [
    "Penetration Tester",
    "Cybersecurity Analyst",
    "Security Engineer"
  ],
  "Graphic Designer": [
    "UI/UX Designer",
    "Motion Graphics Designer",
    "Product Designer",
    "Illustrator"
  ],
  "UI/UX Designer": [
    "Graphic Designer",
    "Frontend Developer",
    "Product Designer"
  ],
  "Database Administrator": [
    "Backend Developer",
    "SQL Developer",
    "Cloud Engineer"
  ],
  "Cloud Engineer": [
    "DevOps Engineer",
    "Database Administrator",
    "AWS Engineer"
  ],
  "DevOps Engineer": [
    "Cloud Engineer",
    "Software Engineer",
    "Site Reliability Engineer"
  ],
  "Project Manager": ["Scrum Master", "Product Manager", "Business Analyst"],
  "Business Analyst": ["Project Manager", "Data Analyst", "Product Manager"],
  "Data Analyst": ["Business Analyst", "Data Scientist", "SQL Developer"],
  "HR Manager": [
    "Recruiter",
    "Talent Acquisition Specialist",
    "Organizational Development Specialist"
  ],
  "Marketing Manager": [
    "Digital Marketing Specialist",
    "SEO Specialist",
    "Content Writer"
  ],
  "Product Manager": [
    "Digital Transformation Consultant",
    "Scrum Master",
    "UI/UX Designer"
  ],
  "Financial Analyst": [
    "Investment Banker",
    "Accountant",
    "Stock Market Analyst"
  ],

  // Engineering & Sciences
  "Mechanical Engineer": [
    "Automotive Engineer",
    "Manufacturing Engineer",
    "Aerospace Engineer"
  ],
  "Electrical Engineer": [
    "Electronics Engineer",
    "Embedded Systems Engineer",
    "Telecommunication Engineer"
  ],
  "Civil Engineer": [
    "Structural Engineer",
    "Geotechnical Engineer",
    "Construction Manager"
  ],
  "Biomedical Engineer": [
    "MedTech Engineer",
    "Bioinformatics Specialist",
    "Biotechnologist"
  ],

  // Healthcare & Wellness
  "Doctor": ["Surgeon", "Dentist", "Nurse"],
  "Nurse": ["Doctor", "Paramedic", "Occupational Therapist"],
  "Psychologist": ["Counselor", "Social Worker", "Behavioral Therapist"],
  "Pharmacist": ["Medical Researcher", "Biochemist", "Doctor"],

  // Creative & Art
  
  "Photographer": ["Videographer", "Photo Editor", "Filmmaker"],
  "Writer": ["Editor", "Copywriter", "Content Writer"],
  "Musician": ["DJ", "Audio Engineer", "Sound Engineer"],
  "Fashion Designer": ["Tailor", "Textile Designer", "Makeup Artist"],

  // Construction & Trades
  "Carpenter": ["Mason", "Furniture Designer", "Construction Worker"],
  "Plumber": ["HVAC Technician", "Electrician", "Maintenance Technician"],
  "Electrician": [
    "HVAC Technician",
    "Renewable Energy Engineer",
    "Construction Worker"
  ],
  "Painter": ["Interior Designer", "Mural Artist", "Wallpaper Installer"],
  "Welder": ["Metal Fabricator", "Blacksmith", "Construction Worker"],

  // Hospitality & Events
  "Chef": ["Caterer", "Restaurant Manager", "Baker"],
  "Baker": ["Pastry Chef", "Caterer", "Food Scientist"],
  "Event Planner": ["Wedding Planner", "Caterer", "Florist"],
  "Wedding Planner": ["Event Planner", "Photographer", "Makeup Artist"],
  "Hotel Manager": ["Hospitality Manager", "Travel Agent", "Tour Guide"],
  "Bartender": ["Mixologist", "Barista", "Waiter"],

  // Logistics & Transportation
  "Truck Driver": ["Delivery Driver", "Warehouse Manager", "Taxi Driver"],
  "Taxi Driver": ["Rideshare Driver", "Chauffeur", "Bus Driver"],
  "Pilot": ["Air Traffic Controller", "Flight Attendant", "Aerospace Engineer"],

  // Farming & Environment
  "Farmer": [
    "Agricultural Engineer",
    "Horticulturist",
    "Environmental Scientist"
  ],
  "Florist": ["Gardener", "Botanist", "Event Planner"],
  "Landscaper": ["Gardener", "Irrigation Specialist", "Urban Planner"],

  // Education & Social Work
  "Teacher": ["Professor", "Tutor", "Educational Consultant"],
  "Professor": ["Researcher", "Author", "Public Speaker"],
  "Social Worker": ["Counselor", "NGO Coordinator", "Psychologist"],

  // Security & Law
  "Lawyer": ["Legal Consultant", "Judge", "Corporate Attorney"],
  "Police Officer": ["Security Guard", "Private Investigator", "Detective"],
  "Security Guard": [
    "Bodyguard",
    "Private Investigator",
    "Law Enforcement Officer"
  ],

  // Entertainment & Media
  "Actor": ["Comedian", "Voice Actor", "TV Presenter"],
  "Comedian": ["Actor", "Talk Show Host", "Scriptwriter"],
  "DJ": ["Musician", "Audio Engineer", "Event Host"],

  // Miscellaneous
  "Barista": ["Bartender", "Café Manager", "Baker"],
  "Yoga Instructor": ["Personal Trainer", "Wellness Coach", "Physiotherapist"],
  "Zoologist": ["Veterinarian", "Wildlife Biologist", "Ecologist"]
};
